### ISSUE TITLE
Password requirements are too complex

### ISSUE THREAD

**Issue by stuarteberg** [JaneliaSciComp/neuronbridge#1]
(I don't like to be "that guy" but at some point we must all make peace with who we are.)

The neuronbridge site requires a password that meets all of the following requirements:

- has minimum length
- contains lowercase letters
- contains uppercase letters
- contains numbers
- contains special characters

According to [NIST password guidelines][1], it is against best practice to require any of those except for the first (minimum length).

To be fair, I could make this same criticism of many of the services I use on the internet, but for most of them I'm not sure where to register the complaint.  You all, on the other hand, have the misfortune of being my colleagues, and I have access to your issue tracker.

[1]: https://securityboulevard.com/2019/03/nist-800-63-password-guidelines

**Comment by neomorphic** [comment]
Those restrictions are put in place by Amazon, so we have no control of those either. Use a google account and you don't need a password.

**Comment by stuarteberg** [comment]
Fair enough!
